services:
  nba-downloader:
    build: .
    container_name: nba-downloader
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Dublin
